apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-sample
  labels:
    app: kub-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kub-sample
  template:
    metadata:
      labels:
        app: kub-sample
    spec:
      containers:
      - name: kub-sample
        image: vishnuoum/kub-sample
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kub-sample-service
spec:
  type: NodePort
  selector:
    app: kub-sample
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010